### ISSUE TITLE
Does not work here

### ISSUE THREAD

**Issue by yisheng** [hanneskuettner/directus-extension-group-tabs-interface#10]
Firstly, thanks for your extension, the screenshots look great!

But, it does not work on my server, any idea? Thanks.

![1](https://github.com/hanneskuettner/directus-extension-group-tabs-interface/assets/352986/4c900dd3-8651-4938-ad7e-8a3cc0e672d5)

![2](https://github.com/hanneskuettner/directus-extension-group-tabs-interface/assets/352986/7d78390a-e9b9-473b-8c9d-f963743e2dca)

**Comment by hanneskuettner** [comment]
Hi!

Do you have any custom themes enabled? I tried the extension (just now, installed from the market place) with all the default themes and it looks perfectly normal on my end.

**Comment by yisheng** [comment]
Thanks for your quick response!

I tried again using the lastest directus (10.10.1), and the UI is normal now.

But I can't accomplish the UI in your screenshots. In the screenshot below, `Status` and `Published in Language` fields are in the `Base Data` group.

![](https://github.com/hanneskuettner/directus-extension-group-tabs-interface/raw/main/docs/screenshot-dark.png)

However, in my screenshot below, `A`, `B`, `C` and `D` are four fields. Something wrong? Thanks again!

<img width="835" alt="image" src="https://github.com/hanneskuettner/directus-extension-group-tabs-interface/assets/352986/412efed4-f7dd-43b2-af49-08cad8e33a86">

<img width="831" alt="image" src="https://github.com/hanneskuettner/directus-extension-group-tabs-interface/assets/352986/c4808373-5071-4b9c-aca4-8e29519031e8">

**Comment by hanneskuettner** [comment]
The trick is to use a "Raw Group" group that you can name and group more than one item under. Let me know if that works for you!

**Comment by yisheng** [comment]
Works fine, Thanks Hannes 👍
