### ISSUE TITLE
Strange overflow when a lot of tabs with preview

### ISSUE THREAD

**Issue by emilienbidet** [hanneskuettner/directus-extension-group-tabs-interface#2]
Hello @hanneskuettner !

Today I have a front end issue using the goup tabs interface.

I have 6 tabs with 8 characters each for the title. When I click on the item preview (recent feature of Directus), the whole page become scrollable. I wanted to know if it's the desired behaviour. If no, I suggest making the group tabs scrollable only the list of tabs if possible.

Here is an example :

![CleanShot 2023-06-26 at 14 33 56](https://github.com/hanneskuettner/directus-extension-group-tabs-interface/assets/44983373/51dd5eaa-5cd2-4c71-a72d-f0dfd729d1cd)

Thank you very much
Bye 
Emilien

**Comment by hanneskuettner** [comment]
That definitely was not intended, it just slipped my review. Thank you for contributing a fix!
