### ISSUE TITLE
Does not respect Field Visibility

### ISSUE THREAD

**Issue by luigigorlero** [hanneskuettner/directus-extension-group-tabs-interface#9]
I’m setting up a Group field with conditional visibility inside the Tab Group; when the condition is met, Directus hides the field (nothing inside is shown), but the Tab menu entry is still visible

**Comment by hanneskuettner** [comment]
Thanks for reporting this!

Fixed in v2.0.1

**Comment by luigigorlero** [comment]
Amazing, works like a charm :) Thanks a lot for this!
